

###POST to add lens:

POST http://localhost:3001/api/lenses
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NDU0N2ZhNDQwYTZjZmI1YjZjYmRkMCIsImlhdCI6MTY4NTg5NDg0NywiZXhwIjoxNjg4NDg2ODQ3fQ.n7KjX6K1L6itvpH-IcHpok3QKFBb7Cs6RKqT_qA9igE

{
    "name": "1.5 UV400",
    "category":"production",
    "index": 1.5,
    "diameter": "90",
    "sphRange": {
        "minus": [-6],
        "plus": [6]
    },
    "cylMax":null,
    "coating": "none",
    "price": 350
}

### GET all lenses
GET http://localhost:3001/api/lenses



###POST to add user:
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "username":"lea",
    "email":"leamor96@gmail.com",
    "password":"Pricer@1234!!"
}

###POST to signin user:
POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
    "email":"leamor96@gmail.com",
    "password":"Pricer@1234!!"
}


###POST to submit form and calculate lens options:
POST http://localhost:3001/api/submit-form
Content-Type: application/json

{
  "sphRight": -2.5,
  "cylRight": -4.75,
  "sphLeft": -3,
  "cylLeft": -3.75
}




