
###POST to add lens:

POST http://localhost:3001/api/lenses
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTAzZjM5NTk4NjcyODM5NTU4NjlkMiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4NzE3ODI0NiwiZXhwIjoxNjg5NzcwMjQ2fQ.QhF_oJ1UzjIQUHMoF8LSkgOC6D2BtSsx-3Em4bpsFms

{
    "name": "1.5 UV400",
    "category":"production",
    "index": 1.5,
    "diameter": "90",
    "sphRange": {
        "minus": [-6],
        "plus": [6]
    },
    "cylMax":null,
    "coating": "none",
    "price": 350
}

### GET all lenses
GET http://localhost:3001/api/lenses

### GET all pro-lenses
GET http://localhost:3001/api/lenses



###POST to add user:
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "username":"lea",
    "email":"leamor96@gmail.com",
    "password":"Pricer@1234!!"
}

###POST to signin user:
POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
    "email":"leamor96@gmail.com",
    "password":"Pricer@1234!!"
}

###POST to signin user:
POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
    "email":"test96@gmail.com",
    "password":"Pricer@1234!!"
}


###POST to submit form and calculate lens options:
POST http://localhost:3001/api/submit-form
Content-Type: application/json

{
  "sphRight": -2.5,
  "cylRight": -4.75,
  "sphLeft": -3,
  "cylLeft": -3.75
}


###POST to add proLens:

POST http://localhost:3001/api/pro-lenses
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODhhYTcxMGJlZjQwZDVjNzljOWJkNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4NjkyNTA5MiwiZXhwIjoxNjg5NTE3MDkyfQ.oVxh2z4XymO6Lnine42MXDw8zoHPlziim-YiO4d3e8s

{
    "name": "STEPPER",
    "lensType":"Transitions gray",
    "index": 1.74,
    "diameter": "90",
    "sphRange": {
        "minus": [-15],
        "plus": [11]
    },
    "adjustmentHeight":"14/15/17/18",
    "coating": "SN",
    "price": 4350
}


###POST to add lens to favorites:
POST http://localhost:3001/api/pro-lenses/6488aa710bef40d5c79c9bd4/favorite/648c6f8990330c74fedf57a5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODhhYTcxMGJlZjQwZDVjNzljOWJkNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4NzE2MTQ0MSwiZXhwIjoxNjg5NzUzNDQxfQ.JSjUUtK55qntBgTRP4qNq-hVtx8T4ajp3hYmHMrvQBY

###GET all favorite lenses
GET http://localhost:3001/api/lenses/6488aa710bef40d5c79c9bd4/favorites
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODhhYTcxMGJlZjQwZDVjNzljOWJkNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4NzE2MTQ0MSwiZXhwIjoxNjg5NzUzNDQxfQ.JSjUUtK55qntBgTRP4qNq-hVtx8T4ajp3hYmHMrvQBY


###POST to add user:
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "username":"mish",
    "email":"mish@gmail.com",
    "password":"Mish@1234!!"
}


###PUT to add lens:

PUT http://localhost:3001/api/lenses/64789695752316b16f5afac5
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTAzZjM5NTk4NjcyODM5NTU4NjlkMiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4NzE3ODI0NiwiZXhwIjoxNjg5NzcwMjQ2fQ.QhF_oJ1UzjIQUHMoF8LSkgOC6D2BtSsx-3Em4bpsFms

{
    "name": "1.5 CYL-2.00 edit",
    "category":"stock",
    "index": 1.5,
    "diameter": "(+)65/(-)70",
    "sphRange": {
        "minus": [-6],
        "plus": [6]
    },
    "cylMax":-2,
    "coating": "none",
    "price": 85
}


###DELETE lens by id
DELETE http://localhost:3001/api/lenses/649058dfe6334790b8776c60
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTAzZjM5NTk4NjcyODM5NTU4NjlkMiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4NzE3ODI0NiwiZXhwIjoxNjg5NzcwMjQ2fQ.QhF_oJ1UzjIQUHMoF8LSkgOC6D2BtSsx-3Em4bpsFms


###DELETE lens by id
DELETE http://localhost:3001/api/lenses/64903f3959867283955869d2/delete-from-favorite/64789ac1752316b16f5afadb
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTAzZjM5NTk4NjcyODM5NTU4NjlkMiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4NzE3ODI0NiwiZXhwIjoxNjg5NzcwMjQ2fQ.QhF_oJ1UzjIQUHMoF8LSkgOC6D2BtSsx-3Em4bpsFms