
###GET login page

GET http://localhost:3001/api/login

###POST to add lens:

POST http://localhost:3001/api/lenses
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NDU0N2ZhNDQwYTZjZmI1YjZjYmRkMCIsImlhdCI6MTY4NTQ4MTc5NSwiZXhwIjoxNjg4MDczNzk1fQ.3abPLNo4bTfv4bT7rDxY7e73Aovwo8-70cvGvQe457Y

{
    "name":"1.5 FLAT55 CYL-2.00",
    "index":"1.5",
    "diameter":"(+)55",
    "minusRange":"0",
    "plusRange":"+1 +8",
    "coating":"none",
    "price":250
}

### GET all lenses
GET http://localhost:3001/api/lenses

###PUT to update a lens:
PUT http://localhost:3001/api/:id
Content-Type: application/json

{
"name":"1.5 CYL-3.00",
"index":"1.6",
"diameter":"(+)65/(-)70",
"minusRange":"-6",
"plusRange":"+4",
"coating":"blue",
"price":250
}

###POST to add user:
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "username":"lea",
    "email":"leamor96@gmail.com",
    "password":"Pricer@1234!!"
}

###POST to signin user:
POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
    "email":"leamor96@gmail.com",
    "password":"Pricer@1234!!"
}


###POST to submit form and calculate lens options:
POST http://localhost:3001/api/submit-form
Content-Type: application/json

{
"sphRight": -2.5,
"cylRight": -1.75,
"sphLeft": -1.75,
"cylLeft": -2.25
}